### ISSUE TITLE
Resolve websocket warning

### ISSUE THREAD

**Issue by SergioEstevao11** [NIAEFEUP/tts-fe#131]
TTS gives WebSocket warnings in the browser console from an unknown origin. This needs to be resolved since WebSocket isn't even being used by the project, so this warning comes from legacy code most likely.
![image](https://user-images.githubusercontent.com/63104941/216599117-e2dc9d4f-0ab8-49ab-b3d4-95b5b2f84590.png)

**Comment by diogotvf7** [comment]
In the last meeting we came to the conclusion that this was happening due to the fact that the application running on server was on dev mode.
