### ISSUE TITLE
Course Units Selection Modal Redesign

### ISSUE THREAD

**Issue by diogotvf7** [NIAEFEUP/tts-fe#182]
# Why
In order to embrace the changes to be implemented on #181 and to simplify the user experience and code of TTS, the Course Units Selection Modal must be redesigned.

# New Design
This is a provisory mockup for the new Course Units Selection Modal (the most recent version can be found on out [Figma](https://www.figma.com/file/GXGcknR29pHx2Fsl0GXvav/TTS?type=design&node-id=0-1&mode=design&t=noPbRyMbALsTTM4A-0))
This new design doesn't need to have a main major. The user can simply search for a major and the picked course_units will be displayed on the right side of the modal, it's information will be fetched and stored on the Local Storage. 
![2024-01-26-00:04:38](https://github.com/NIAEFEUP/tts-revamp-fe/assets/93603699/c7fbc708-a51a-48a2-8be1-de27333097a3)

**Comment by tomaspalma** [comment]
It is already done on branch #198
