### ISSUE TITLE
Update Classes Types on Schedule Caption

### ISSUE THREAD

**Issue by diogotvf7** [NIAEFEUP/tts-fe#206]
# What's the problem
We currently have buttons that toggle the visibilty of a certain type of class:
| Classes Visible | Classes hidden |
| --------------------- | ---------------------- |
|  ![2024-03-05-14:24:01](https://github.com/NIAEFEUP/tts-fe/assets/93603699/d7c46697-1b6a-4399-a733-490936394128) | ![2024-03-05-14:24:07](https://github.com/NIAEFEUP/tts-fe/assets/93603699/9e29480c-8ba0-4e38-9c99-da5a0e51deda) |

The problem with this is that the caption's interaction isn't very clear (many people don't understand that the class type names are buttons as well). 

# Main goal for this issue
The main goal for this issue is to make the the buttons UI more obvious. This might be achieved by simply making using of the already existing checkbox component and changing the color to the specific class type color.

**Comment by tomaspalma** [comment]
It was merged with in the #198 pull request
